name: Global CI

on:
  push:
    branches:
      - main
      - "release-*"
  pull_request:
    branches:
      - main
      - "release-*"
  workflow_dispatch:
  workflow_call:

jobs:
  e2e:
    uses: trustification/trustify-ui/.github/workflows/ci-global-template.yaml@main
    with:
      run_api_tests: true
      run_ui_tests: true
      tests_ref: ${{ github.event.number && format('refs/pull/{0}/merge', github.event.number) || '' }}
